### ISSUE TITLE
Variable 'tensor_names' referenced before assignment

### ISSUE THREAD

**Issue by sidmani** [Stonesjtu/pytorch_memlab#22]
https://github.com/Stonesjtu/pytorch_memlab/blob/ec9a72fc302981ddc3ee56d6e16694610d646c36/pytorch_memlab/mem_reporter.py#L37

The variable tensor_names is referenced before assignment if no model is passed into the MemReporter. Need to move it into the above if statement.

**Comment by Stonesjtu** [comment]
Thanks for reporting this issue, will do this week.
