### ISSUE TITLE
Fail to install using pip

### ISSUE THREAD

**Issue by XikunZhang** [Stonesjtu/pytorch_memlab#29]
I tried to install using `pip install `or `pip install git+https://github.com/stonesjtu/pytorch_memlab` and in both cases got this error:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sx0xf6jy/pandas/setup.py", line 333
        f"{extension}-source file '{sourcefile}' not found.\n"
                                                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sx0xf6jy/pandas/
```

**Comment by Stonesjtu** [comment]
It looks like the installation of pandas failed, could you plz try pip install pandas first and see if the error still exists.

**Comment by XikunZhang** [comment]
Yeah, I tried that and the error still exists.

**Comment by Stonesjtu** [comment]
It's probably because you are using the **pip of python2** and python2 does not support *f-string* AFAIK. Can you try the python3 version via `pip3 install xxx`.

**Comment by XikunZhang** [comment]
`pip3` does not work either. I solved this by upgrading my `pip`. Previously it was version `8.1.1`, and now it is `20.3.1`. Thanks for the reply though!
