### ISSUE TITLE
ImportError: cannot import name 'set_target_gpu'

### ISSUE THREAD

**Issue by ProGamerGov** [Stonesjtu/pytorch_memlab#3]
I installed `pytorch_memlab` with `pip3 install pytorch_memlab` and I get this error when trying to set the target GPU:

```
    from pytorch_memlab import profile, set_target_gpu
ImportError: cannot import name 'set_target_gpu'
```

**Comment by Stonesjtu** [comment]
The newest package is not uploaded to *pip* yet.
Can you plz try install from source via

```bash
pip install git+https://github.com/stonesjtu/pytorch_memlab
```

**Comment by Stonesjtu** [comment]
I just uploaded the current master to PyPI. you can try to update the package by `pip install -U pytorch_memlab`.

Can you please verify if the problem exists with the newest package?

**Comment by Stonesjtu** [comment]
Should be fixed, I'm closing this issue.
Please feel free to re-open if the problem still exists with the newest release.
