### ISSUE TITLE
is PyTorch Profiler Used Internally?

### ISSUE THREAD

**Issue by yzhao062** [Stonesjtu/pytorch_memlab#39]
Great repository! Thanks for creating this :)
Just have a quick question. Is pytorch_memlab tracking the memory usage by torch.autograd.profiler? thanks a lot! Just want to clarify this to see if I need to use both :)

**Comment by yzhao062** [comment]
from the code I think it is using torch.cuda.memory_stats()
Hope my understanding is correct!

**Comment by Stonesjtu** [comment]
It's not tracking `torch.autograd.profiler`. The profiling level of this tool is **line** of python code, while `torch.autograd.profiler` is torch operation level.

**Comment by yzhao062** [comment]
Thanks a lot for the clarification!
