### ISSUE TITLE
Question about Used Memory and GPU memory

### ISSUE THREAD

**Issue by lfangyu09** [Stonesjtu/pytorch_memlab#44]
Hi,

Thanks a lot for providing this very helpful library.
I have a question about Used Memory and GPU memory.
I followed your code to get the Used Memory of my model for one batch (size: (16, 3, 224, 224)). It is 928.02M. But the same code for the same model could not run in 2070 super GPU (8 GiB capacity). 
928.02 M vs 8 GiB. What is the difference between the Used Memory in your code and GPU memory? Thanks.

Here are the running results.
![image](https://user-images.githubusercontent.com/62622741/152660400-15830bc6-bf2c-4ad7-8f89-b871b2bf6a5a.png)
![image](https://user-images.githubusercontent.com/62622741/152660404-d9260db4-49df-4bae-af05-d3bb8e71459e.png)

**Comment by Stonesjtu** [comment]
Are you printing the memory usage after `backward` (BP)?

Used memory collects all the PyTorch Tensors in ** Python ** language space.

**Comment by lfangyu09** [comment]
I have made a comparison for the same model between the Used Memory by your code and GPUtil. Here are the results.
The Used Memory is 409M and GPU memory by GPUtil is 6786 MiB.
Is the Used Memory by your code not the GPU memory? I am confused by "all the PyTorch Tensors in ** Python ** language space.". Is there any tutorial to explain it in detail? Thanks a lot!

![image](https://user-images.githubusercontent.com/62622741/153092724-3b8ec8e6-d9e6-45f1-920f-486b900ff27f.png)
![image](https://user-images.githubusercontent.com/62622741/153092776-845f736e-d242-406b-bc93-6ae32df52b1b.png)

**Comment by Stonesjtu** [comment]
You can place the `report()` before `backward()`; The GPUtil gets the memory PyTorch **requests** (or cached), while memory_reporter gets the memory PyTorch actually **allocated**
