### ISSUE TITLE
Does the @profile decorator affect memory usage?

### ISSUE THREAD

**Issue by sryo200** [Stonesjtu/pytorch_memlab#63]
I added the `@profile` decorator to the method of the class I use for training deep learning models. However, when I checked the memory usage with `nvtop`, I noticed that memory consumption decreased compared to before adding the decorator. Additionally, surprisingly, the run time also seemed to be shorter. I initially thought that the Memory Profiler only tracks memory usage, but does it actually influence memory usage?

Thank you!

**Comment by Stonesjtu** [comment]
The line-profiler makes a `torch.cuda.empty_cache()` call after every lines of the function being decorated.
So probably you have too many memory fractions and *allocating* \ *freeing* cuda memory may cost considerable time in this case.

**Comment by sryo200** [comment]
Thank you for your detailed explanation!
It clarified my doubts and gave me a good opportunity to review my implementation.
